syscoin/pali-mobile

- app/app/components/Main/MainNavigator.js
> fix: remove bottom nav bar texts

- app/app/components/Main/MainNavigator.js
- app/app/components/Views/Settings/index.js
> fix: remove observe account tab

- app/app/components/UI/SecurityView/index.js
> fix: solves account address overflow

- app/app/components/Views/DeveloperOptions/index.js
> feat: developer options order

- app/app/components/Views/WalletManagement/index.js
> feat:  improves wallets separation

- app/app/components/Views/QRScanner/index.js
> feat: add qrcode back button

- app/app/components/Main/MainNavigator.js
- app/app/components/Views/Settings/index.js
- app/app/components/Views/Wallet/index.js
> feat: add settings assets header

- app/app/components/Main/MainNavigator.js
- core/src/Config.ts
> fix: solves settings screen animation & removes ethereum tesnets.

- app/app/components/Main/MainNavigator.js
> fix: solves default right-to-left animation 

- app/app/components/Main/index.js
- app/app/components/UI/Tokens/index.js
- app/app/components/UI/TransactionsView/index.js
- app/app/components/Views/AboutView/index.js
- app/app/components/Views/CurrencyUnit/index.js
- app/app/components/Views/DeveloperOptions/index.js
- app/app/components/Views/SecuritySettings/index.js
- app/app/components/Views/SimpleWebview/index.js
- app/app/components/Views/UpdateCheck/index.js
- app/app/components/Views/WalletManagement/index.js
> feat: adds switch animation and removes unnecessary safeareaProviders

- core/src/Config.ts
> feat: add rollux testnet

- app/app/components/UI/Tokens/index.js
> fix: solves token switch bug

- README.md
- app/app/components/Views/AboutView/index.js
> feat: updates social media links

- app/app/components/Main/MainNavigator.js
- app/app/components/Views/SendFlow/SendTab/index.js
> feat: adds vibration

- app/app/components/UI/CardSwiper/index.js
- app/app/components/UI/GlobeIcon/index.js
- app/app/components/Views/WalletManagement/index.js
- app/app/util/favoritesList.js
- app/app/util/suggestedWebsites.js
> feat: update logos

- README.md
- app/app/components/Main/MainNavigator.js
- app/app/components/Views/SendFlow/SendTab/index.js
- app/ios/GoPocket.xcodeproj/project.pbxproj
- app/ios/GoPocket/Base.lproj/LaunchScreen.xib
> refactor(ios): changes bundle id and splash screen and removes vibration

- app/app/components/Views/DrawingBoard/index.js
- app/app/components/Views/WalletManagement/index.js
- app/app/styles/common.js
- app/ios/Podfile
- core/src/Config.ts
- core/src/keyring/HdKeyring.ts
- core/src/keyring/KeyringController.ts
- core/src/keyring/KeyringControllerImpl.ts
> feat: imported and created account

- app/.gitignore
- app/android/app/google-services.json
> refactor: google config

- app/app/components/Views/OpenedTabs/index.js
> fix: animation order openedTabs

- app/app/components/Views/Asset/index.js
> fix(Asset): solves linear gradient crash

- app/android/app/src/main/AndroidManifest.xml
- app/app/components/Views/BrowserTab/index.js
- app/app/components/Views/OpenedTabs/index.js
- app/app/core/AppConstants.js
- app/app/core/AutoCompleteController.js
- app/app/core/DeeplinkManager.js
- app/ios/GoPocket.xcodeproj/project.pbxproj
- app/ios/GoPocket.xcodeproj/xcshareddata/xcschemes/GoPocket.xcscheme
- app/ios/GoPocket/GoPocket.entitlements
- app/ios/GoPocket/GoPocketDebug.entitlements
- app/ios/Podfile
> feat: updates entitlement

- app/app/components/UI/AssetView/index.js
- app/app/components/UI/TokenImage/index.js
- app/app/util/rolluxIntro.js
- core/src/Config.ts
> feat: updates rollux token icons and rollux intro and rollux network config

- app/android/app/build.gradle
- app/app/store/migrations.js
- app/ios/PaliWallet.xcodeproj/project.pbxproj
- core/src/Config.ts
> feat: Rollux migration

- core/src/assets/StaticTokenController.ts
> feat: update tokens api

- core/src/Config.ts
> feat: updates rollux contract addresses

- app/android/app/build.gradle
- app/app/util/luxy.js
- app/ios/PaliWallet.xcodeproj/project.pbxproj
- core/src/Config.ts
- core/src/assets/CollectiblesController.ts
> feat: Adds rollux nfts

- app/android/app/build.gradle
- app/app/components/UI/AccountApproval/index.js
- app/app/components/UI/WalletConnectList/index.js
- app/app/core/DeeplinkManager.js
- app/app/core/WalletConnect/WalletConnectV2.js
- app/app/util/walletconnect.js
- app/ios/PaliWallet.xcodeproj/project.pbxproj
- app/package.json
- app/yarn.lock
> fix: wc login issues and deeplink redirect issues

- app/app/components/Main/index.js
- app/app/core/WalletConnect/WalletConnectV2.js
> Feat: Improves support for add chain user flow on Wallet Connect

- app/app/components/Main/index.js
- app/app/core/WalletConnect/WalletConnectV2.js
> refactor: turns listeners off when unmounting

- app/android/app/build.gradle
- app/android/app/src/main/java/io/gopocket/MainApplication.java
- app/android/settings.gradle
- app/app/components/Main/MainNavigator.js
- app/app/components/UI/MessageSign/index.js
- app/app/components/UI/PersonalSign/index.js
- app/app/components/UI/SecurityView/ApprovalTop.js
- app/app/components/UI/SecurityView/SecurityTop.js
- app/app/components/UI/TypedSign/index.js
- app/app/components/Views/FoldSecurityView/index.js
- app/app/components/Views/ResetPassword/index.js
- app/app/components/Views/SendFlow/SendTab/index.js
- app/app/components/Views/Wallet/index.js
- app/package.json
- app/yarn.lock
> feat: add vibration

- app/app/components/Main/index.js
- app/app/components/UI/HomePage/index.js
- app/app/components/Views/Settings/index.js
- app/app/components/Views/UpdateCheck/index.js
- app/app/util/NativeUtils.js
> feat: adds changelog & update check

- app/app/util/number.js
On this PR i changed the code to change the comma to dot instead of remove the input
> Fix: changing comma to dot on decimal-pad

- app/app/components/UI/NFTImage/index.js
On this PR i removed the onError func on fastImage component to allow image be loaded correctly
> Chore: removing error catch to alow image finish load

- app/ios/PaliWallet/Info.plist
> feat: increase frame rate limit on IOS

- app/android/app/build.gradle
- app/app/components/UI/AssetView/index.js
- app/app/util/number.js
- app/ios/PaliWallet.xcodeproj/project.pbxproj
> fix: asset chart loading

- app/app/components/Views/DrawingGuide/index.js
- app/app/components/Views/LanguageSelector/index.js
- app/app/components/Views/NftView/index.js
- app/app/components/Views/Root/index.js
- app/app/components/Views/WalletManagement/index.js
- app/locales/es.json
- app/locales/i18n.js
> feat: adds the default user language as the app default

- app/app/components/UI/TypedSign/index.js
> fix: transaction modal overflow

- app/app/components/UI/NFTImage/index.js
> fix : nft image not loading

- app/app/components/UI/Nft/index.js
> fix: solves error on thumbnail_url value

- app/app/components/UI/ChainSettingView/index.js
- app/app/components/UI/TransactionTips/index.js
- app/app/components/Views/Wallet/index.js
- app/app/core/EngineImpl.js
- core/src/assets/TokenBalancesController.ts
> feat: improves rollux update time to 20 seconds

- app/app/components/UI/ApproveTransactionReview/index.js
- app/app/components/Views/ApproveView/Approve/index.js
- app/locales/en.json
- app/locales/es.json
- app/locales/zh-cn.json
> feat: adds approval security api for approval and revoke transactions

- app/app/components/Views/ImportFromSeed/index.js
- app/app/components/Views/ImportPrivateKey/index.js
- core/src/user/EnsController.ts
> fix: multiple ens names

- app/app/components/UI/NFTImage/index.js
- app/app/components/Views/NftView/index.js
> feat: nft video fallback

- core/src/assets/CollectiblesController.ts
> fix: solves rollux token nft collection not appearing

- app/app/components/Views/MediaPlayer/index.js
- app/app/components/Views/NftView/index.js
- app/package.json
> feat: adds fallback for thumbnail url on mediaPlayer

- app/app/components/Views/SendFlow/AmountSection/index.js
- app/app/components/Views/SendFlow/MoveTab/index.js
- app/app/components/Views/SendFlow/SendNFTTab/index.js
> fix: decimal spanish

- app/android/app/build.gradle
- app/app/components/Views/BrowserTab/index.js
- app/ios/PaliWallet.xcodeproj/project.pbxproj
- app/locales/en.json
- core/src/Config.ts
> fix: solves wallet connect redirect bug and rollux explorer
